#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     p1c1m1,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     p1c1m2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     p1c2m1,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_2,     p1c2m2,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     p1c3m1,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     p1c3m2,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     p1c4m1,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     p1c4m2,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    p2c1s1,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    p2c1s2,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    p2c1s3,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    p2c1s4,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_5,    p2c1s5,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_6,    p2c1s6,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_1,    p2c2s1,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    p2c2s2,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    p2c2s3,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_4,    p2c2s4,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_5,    p2c2s5,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_6,    p2c2s6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Autonomous Mode Code Template
//
// This file contains a template for simplified creation of an autonomous program for an TETRIX robot
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"
#include "lift.h"
#include "debug.h"
#include "lib6460\libfcs.h"
  //Include file to "handle" the Bluetooth messages.
#include "drive_movement.h"
#include "harvester.h"
#include "music.h"
/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of autonomous mode, you may want to perform some initialization on your robot.
// Things that might be performed during initialization include:
//   1. Move motors and servos to a preset position.
//   2. Some sensor types take a short while to reach stable values during which time it is best that
//      robot is not moving. For example, gyro sensor needs a few seconds to obtain the background
//      "bias" value.
//
// In many cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
  // Place code here to sinitialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
	initDrive();
	closeDispenser();
	startupDebug();
	initDeCesare();
	stowAssist();
  return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the autonomous robot operation. Customize as appropriate for
// your specific robot.
//
// The types of things you might do during the autonomous phase (for the 2008-9 FTC competition)
// are:
//
//   1. Have the robot follow a line on the game field until it reaches one of the puck storage
//      areas.
//   2. Load pucks into the robot from the storage bin.
//   3. Stop the robot and wait for autonomous phase to end.
//
// This simple template does nothing except play a periodic tone every few seconds.
//
// At the end of the autonomous period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
  initializeRobot();

  waitForStartOrButton(); // Wait for the beginning of autonomous phase.

  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////
  ////                                                   ////
  ////    Add your robot specific autonomous code here.  ////
  ////                                                   ////
  ///////////////////////////////////////////////////////////
  ///////////////////////////////////////////////////////////

  updateSpeed(-60,-100,0);
  wait1Msec(3600);
  updateSpeed(0,0,0);
  grabGoal();
  wait1Msec(100);
  updateSpeed(0,60,0);
  wait1Msec(800);
  updateSpeed(0,0,0);
  //wait1Msec(50);
  //updateSpeed(60,60,0);
  //wait1Msec(5000);
  //updateSpeed(0,0,0);
  //wait1Msec(50);
  //updateSpeed(60,0,0);
  //wait1Msec(1000);
  while(true);
}
